#%RAML 1.0 NamedExample

value:
  -
    ID: a0M0n00000303BXEAY
    protocolGroup: a020n0000042bYiAAI
    queryString: first_name AS First_Name__c
  -
    ID: a0M0n00000303BNEAY
    protocolGroup: a020n0000042bYiAAI
    queryString: id AS Name