#%RAML 1.0 NamedExample

value:
  -
    record_id: string
    screener_profile_id: string
    contacted: string
    Reached: tring
    Scheduled: string
    scheduled_date: 2016-02-28
    attended_v1: string
    attended_v1_date: 2016-02-28
    declined_consents: string
    screen_failed: string
    screen_failed_date: 2016-02-28
    randomized: string
    randomized_date: 2016-02-28
    inactive_referral: string
  -
    record_id: string1
    screener_profile_id: string
    contacted: string
    Reached: tring
    Scheduled: string
    scheduled_date: 2016-02-28
    attended_v1: string
    attended_v1_date: 2016-02-28
    declined_consents: string
    screen_failed: string
    screen_failed_date: 2016-02-28
    randomized: string
    randomized_date: 2016-02-28
    inactive_referral: string
