#%RAML 1.0 NamedExample

value:
  -
    first_name__c: first name
    name: name
    referral_id__c: referral_id
    screener_profile_id__c: screener_profile
  -
    first_name__c: first name1
    name: name1
    referral_id__c: referral_id1
    screener_profile_id__c: screener_profile1