#%RAML 1.0 NamedExample



id: id number
items:
  -
    exception: exception message
    message: message
    payload:
      created: false
      success: true
      id: a060n000003bRQFAA2
      errors:
        errorMessage: message
        type: type
    id: a060n000003bRQGAA2
    statusCode: statusCode
    successful: true
  -
    exception: exception message1
    message: message1
    payload:
      created: false
      success: true
      id: a060n000003bRQFAA21
      errors:
        errorMessage: message1
        type: type1
    id: a060n000003bRQGAA21
    statusCode: statusCode1
    successful: true