#%RAML 1.0 NamedExample

week_start_date: 2016-02-28
wave: "wave1" 
spend: 1234
media_source: source
projected_inquiries: 123456
projected_referrals: 1345
projected_appointments: 12345
projected_screened: 12345
projected_randomized: 12345
protocol_group: ab123
country: USA